apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - repoHost:
      github:
        organization: argoproj
      filters:
      - repositoryMatch: example-apps
  template:
    metadata:
      name: '{{ repository }}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: '{{ url }}'
        targetRevision: '{{ branch }}'
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: guestbook
