apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/argoproj/argocd-applicationset
  newName: quay.io/argoproj/argocd-applicationset
  newTag: latest

namespace: argocd

resources:
- deployment.yaml
- rbac.yaml
