run:
  timeout: 5m
  skip-files:
  skip-dirs:
linters:
  enable:
    - vet
    - deadcode
    - goimports
    - varcheck
    - structcheck
    - ineffassign
    - unconvert
    - unparam
output:
  format: github-actions
issues:
  exclude:
    - SA5011
    - S1005
