
site_name: ApplicationSet Controller
site_url: 'https://argocd-applicationset.readthedocs.io/'
repo_url: https://github.com/argoproj/applicationset
use_directory_urls: true
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
extra_javascript:
- js/jquery-2.1.1.min.js
- js/modernizr-2.8.3.min.js
- js/theme.js
markdown_extensions:
- admonition
- pymdownx.highlight
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - Introduction: index.md
  - Getting Started: Getting-Started.md
  - Use Cases: Use-Cases.md
  - How ApplicationSet controller interacts with Argo CD: Argo-CD-Integration.md
  - Generators: 
    - Generators.md
    - Generators-List.md
    - Generators-Cluster.md
    - Generators-Git.md
    - Generators-Matrix.md
    - Generators-Merge.md
    - Generators-SCM-Provider.md
    - Generators-Cluster-Decision-Resource.md
    - Generators-Pull-Request.md
  - Template fields: Template.md
  - Controlling Resource Modification: Controlling-Resource-Modification.md
  - Application Pruning & Resource Deletion: Application-Deletion.md
  - Developer Guide:
    - Building and Running the Controller: Development.md
    - Running E2E Tests: E2E-Tests.md
    - Release Process: Releasing.md
    - Release Checklist Template: Release-Checklist-Template.md
