
site_name: ApplicationSet Controller
repo_url: https://github.com/argoproj-labs/applicationset
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
extra_css:
- assets/extra.css
- css/extra.css
extra_javascript:
- js/jquery-2.1.1.min.js
- js/modernizr-2.8.3.min.js
- js/theme.js
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Introduction: index.md
  - Getting Started: Geting-Started.md
  - Use Case: Use-Cases.md
  - Argo CD Integration: Argo-CD-Integration.md
  - Generators: Generators.md
  - Templates: Template.md
  - Application Deletion: Application-Deletion.md
  - Developer Guide:
    - Running E2E Tests: E2E-Tests.md
    - Release Guidance: Releasing.md


