apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/csouza-harness/applicationset.git
        revision: HEAD
        files:
        - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster_name}}-guestbook'
    spec:
      project: 8f777467
      source:
        repoURL: https://github.com/csouza-harness/applicationset.git
        targetRevision: HEAD
        path: "examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster_address}}'
        namespace: default
      syncPolicy:
        automated: {}
