---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: test-placement
  namespace: argocd
spec:
  clusterSelector:
    matchLabels:
      'usage': 'development'

# Below is sample output the generator DuckType can consume.
status:
  decisions:
  - clusterName: cluster-01
  - clusterName: cluster-02