server:  
  image:
    repository: docker.io

#imagePullSecrets:
#- name: <path:secret/data/sample-secret#first-secret>

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: false
  
pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false
  
alertmanager:
## If false, alertmanager will not be installed
##
  enabled: true
  useClusterRole: false

kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: false

server:
  enabled: false
  useClusterRole: false
  # namespaces:
  #  - cassie-dev