name: Nightly test of ApplicationSet 'master' branch against latest Argo CD 'master' branch
# This is useful for catching recent regressions between master branches of Argo CD and ApplicationSet.

on:
  schedule:
    - cron: '5 2 * * *'

  push:
    branches:
      - 'cron-test-argocd'


jobs:

  test-e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s-version: [v1.20.2]
    env:
      GOPATH: /home/runner/go
      ARGOCD_FAKE_IN_CLUSTER: 'true'
      ARGOCD_SSH_DATA_PATH: '/tmp/argo-e2e/app/config/ssh'
      ARGOCD_TLS_DATA_PATH: '/tmp/argo-e2e/app/config/tls'
      ARGOCD_E2E_SSH_KNOWN_HOSTS: '../fixture/certs/ssh_known_hosts'
      ARGOCD_E2E_K3S: 'true'
      ARGOCD_IN_CI: 'true'
      ARGOCD_E2E_APISERVER_PORT: '8088'
      ARGOCD_SERVER: '127.0.0.1:8088'
      INSTALL_K3S_VERSION: ${{ matrix.k3s-version }}+k3s1
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    steps:
          
      - name: Checkout latest Argo CD code
        uses: actions/checkout@v2
        with:
          repository: argoproj/argo-cd
          ref: master
          path: argo-cd
          
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Restore go build cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}

      - name: Checkout latest applicationset code
        uses: actions/checkout@v2
        with:
          path: applicationset

      - name: Run E2E test setup
        timeout-minutes: 20
        run: |
          cd "$GITHUB_WORKSPACE/applicationset"
          "hack/ci-e2e-setup.sh"

      - name: Run E2E tests
        timeout-minutes: 25
        run: |
          sleep 60s
          cd "$GITHUB_WORKSPACE/applicationset"
          "hack/ci-e2e-run.sh"

      - name: Upload e2e-server logs
        uses: actions/upload-artifact@v2
        with:
          name: appset-e2e-server-k8s${{ matrix.k3s-version }}.log
          path: /tmp/appset-e2e-server.log
        if: ${{ failure() }}
      - name: Upload other Argo CD server log
        uses: actions/upload-artifact@v2
        with:
          name: argocd-e2e-server-k8s${{ matrix.k3s-version }}.log
          path: /tmp/e2e-server.log
        if: ${{ failure() }}
